# Generated by Django 3.1.2 on 2023-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
